In [3]:
import numpy as np

# Matriks koefisien
A = np.array([
    [19, -5, -4,  0],
    [-3,  9,  0, -2],
    [-4,  0, 19, -10],
    [ 0, -1, -3,  6]
], dtype=float)

# Vektor konstanta
b = np.array([60, 24, 20, 15], dtype=float)

# Matriks augmented
aug = np.column_stack((A, b))

def gauss_jordan(matrix):
    M = matrix.astype(float).copy()
    rows, cols = M.shape
    pivot_row = 0

    for pivot_col in range(cols - 1):
        # Cari pivot terbesar secara absolut
        max_row = pivot_row
        for r in range(pivot_row, rows):
            if abs(M[r, pivot_col]) > abs(M[max_row, pivot_col]):
                max_row = r

        # Jika pivot nol, lanjut ke kolom berikutnya
        if abs(M[max_row, pivot_col]) < 1e-12:
            continue

        # Tukar baris jika perlu
        if max_row != pivot_row:
            M[[pivot_row, max_row]] = M[[max_row, pivot_row]]

        # Normalisasi baris pivot
        pivot = M[pivot_row, pivot_col]
        M[pivot_row] = M[pivot_row] / pivot

        # Eliminasi semua elemen lain di kolom pivot
        for r in range(rows):
            if r != pivot_row:
                factor = M[r, pivot_col]
                M[r] = M[r] - factor * M[pivot_row]

        pivot_row += 1
        if pivot_row == rows:
            break

    return M

# Proses Gauss-Jordan
rref = gauss_jordan(aug)

print("Matriks eselon baris tereduksi:")
print(rref)

# Ambil solusi
solution = rref[:, -1]

print("\nSolusi:")
for i, val in enumerate(solution, start=1):
    print(f"V{i} = {val:.6f} volt")

Matriks eselon baris tereduksi:
[[1.         0.         0.         0.         5.93545535]
 [0.         1.         0.         0.         6.05039788]
 [0.         0.         1.         0.         5.63041556]
 [0.         0.         0.         1.         6.32360743]]

Solusi:
V1 = 5.935455 volt
V2 = 6.050398 volt
V3 = 5.630416 volt
V4 = 6.323607 volt


In [4]:
x_check = np.linalg.solve(A, b)

print("Hasil verifikasi:")
for i, val in enumerate(x_check, start=1):
    print(f"V{i} = {val:.6f} volt")

Hasil verifikasi:
V1 = 5.935455 volt
V2 = 6.050398 volt
V3 = 5.630416 volt
V4 = 6.323607 volt
